name: build packages
on:
  push:
    branches:
      - dontrunyet
  workflow_dispatch:
jobs:
  build:
    name: build packages
    runs-on: ubuntu-latest
    steps:
      - name: install secrets 
        shell: bash
        env:
          ID_RSA: ${{secrets.ID_RSA}}
          SSHCONFIG: ${{secrets.SSHCONFIG}}
          GPG_KEY: ${{secrets.GPG_KEY}}
        run: |
          sudo apt update
          sudo apt install -qq gpg openssh-client
          mkdir -p ~/.ssh
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSHCONFIG" > ~/.ssh/config
          echo "$GPG_KEY" | gpg --import
      - name: checkout code
        uses: actions/checkout@v3
      - name: install deps
        shell: bash
        run: |
          sudo apt install -qq rsync podman flatpak elfutils coreutils slirp4netns rootlesskit binfmt-support fuse-overlayfs flatpak-builder qemu-user-static
      - name: build deb
        shell: bash
        env:
          VERSION: "6.16.0"
        run: |
          set -x
          echo "Version is: $VERSION"
          bash ci-build.sh
          podman stop signal-desktop-$VERSION
          cp ~/signal-desktop.deb .
